### PR TITLE
Toggle button

### PR DESCRIPTION
**Pull request by Iankodj**
This continues from [Toggle button](https://github.com/telerik/ajax-docs/pull/60).

### CODE REVIEW

**Comment by erikruth** [comment]
I haven't edited Toggle Button yet. Is it closed or do you want me to edit it?

**Comment by Iankodj** [comment]
Erik, the pull request is not closed and Toggle Button documentation should be edited. Is there something that stops you?

**Comment by erikruth** [comment]
It shows as closed 17 days ago, by you.

**Comment by Iankodj** [comment]
The closed one is #60. The pull request was recreated in #64 due to the new workflow. Therefore, editing on Toggle Button documentation should be done in this pull request (#64).

**Pull request merged**
