### PR TITLE
Radio button list

### PR DESCRIPTION
**Pull request by danail-vasilev**
Please review all the new article in the ajax-docs/controls/radiobuttonlist/ section - https://github.com/telerik/ajax-docs/tree/RadioButtonList/controls/radiobuttonlist

### CODE REVIEW

**Comment by erikruth** [comment]
I edited the overview.md, design-time.md and getting-started.md articles. All of the markdown files have the same date. Which other ones do I edit? I started to edit accessibility and internationalization and they don't need editing. It looks like they are created from slug templates of other articles. So do the appearance and styling articles.

**Comment by danail-vasilev** [comment]
Hi Erik,
Generally most of the articles are copied from the RadCheckbox control articles and modified to resemble the RadRadioButtonList context. That being said it is good to review all of the articles. Nevertheless, there are 3 brand new articles that should be with higher priority for the review:
    - https://github.com/telerik/ajax-docs/blob/RadioButtonList/controls/radiobuttonlist/functionality/layout.md
    - https://github.com/telerik/ajax-docs/blob/RadioButtonList/controls/radiobuttonlist/functionality/select-item.md
    - https://github.com/telerik/ajax-docs/blob/RadioButtonList/controls/radiobuttonlist/data-binding/overview.md

**Comment by erikruth** [comment]
This link:  https://github.com/telerik/ajax-docs/blob/RadioButtonList/controls/radiobuttonlist/data-binding/overview.md is producing a 404 error.

**Comment by danail-vasilev** [comment]
I have changed the name of the article. This is the correct path to the article - https://github.com/telerik/ajax-docs/blob/RadioButtonList/controls/radiobuttonlist/data-binding/server-side-data-binding.md

**Pull request merged**
