### PR TITLE
Added documentaion for RadStandardButton

### PR DESCRIPTION
**Pull request by danail-vasilev**

### CODE REVIEW

**Comment by marin-bratanov** [comment]
in Elastic Design, add sample for page-wide CSS rule and note that the control inherits the font style of the page

**Comment by marin-bratanov** [comment]
on creating a custom skin - is .RadButton the class or should there be .RadPushButton (probably added in addition to .RadButton)

**Comment by marin-bratanov** [comment]
@erikruth Use the RadStandardButton branch and look at the files under controls/pushbutton
the rest of the commits and the branch name are a bit irrelevant.

**Comment by erikruth** [comment]
I am not seeing this. Was this changed or am I not finding it because it was closed?

**Comment by danail-vasilev** [comment]
Again, this is closed. I had some issues with resolving branch conflicts, so I deleted these pull requests and created new ones. Apologize for the inconvenience.

**Pull request closed without merging**
