### PR TITLE
RadImageButton documentation

### PR DESCRIPTION
**Pull request by Iankodj**
review the entire folder:
controls/imagebutton

### CODE REVIEW

**Comment by marin-bratanov** [comment]
Link to image button docs https://github.com/telerik/ajax-docs/tree/ImageButton/controls/imagebutton

**Comment by erikruth** [comment]
That works now. Thank you.

**Comment by Iankodj** [comment]
**REMINDER**: Once **Q1-2016** branch is **removed** this **Pull Request** should be **merged** into master **manually** using **Git Bash**.

**Comment by Iankodj** [comment]
This continues to #65

**Pull request closed without merging**
