### PR TITLE
doc(grid) rework advanced data binding

### PR DESCRIPTION
**Pull request by edrohler**

### CODE REVIEW

**Comment by marin-bratanov** [comment]
See this on constructing the `previous_url` [https://github.com/telerik/ajax-docs/wiki/Handling-Redirects](https://github.com/telerik/ajax-docs/wiki/Handling-Redirects)

Also, is the URL change necessary, the article should be quite popular as it is and I am not aware of problems with it?

**Comment by edrohler** [comment]
@marin-bratanov thanks for that! I didn't' see anything about the `previous_url:` in the internal wiki. As for the change, we are updating the doc per feedback from customers.

**Comment by edrohler** [comment]
> you can use this to test how your redirects work https://github.com/telerik/ajax-docs/wiki/Deploying-Documentation-on-IIS

@marin-bratanov, this is awesome. Build times are like 8-10 minutes and having an IIS version locally is far better than using `jekyll serve` to see changes. Many thanks!

**Comment by marin-bratanov** [comment]
8-10? Wow, you're lucky, or your PC is super powerful :) When I was in the office it took about 20 for me, on my current setup I expect around 40-50.

**Pull request merged**
