### PR TITLE
Update keyboard-support.md

### PR DESCRIPTION
**Pull request by erikruth**
Should you also add the Chrome and Microsoft Edge browser shortcuts? Chrome in particular.

### CODE REVIEW

**Comment by Iankodj** [comment]
Yes, the AccessKey combination in Chrome is the same as in IE. I updated it directly in this pull request. 

As for EDGE, it should be assumed as IE. I don't think there would be a confusion among clients about that.

Let me know if I should merge these changes.

**Comment by marin-bratanov** [comment]
You should propagate them to other buttons documentation, perhaps create a template for reuse.

**Comment by Iankodj** [comment]
Marin, every possible keyboard-support.md article regarding button controls has this update now. 

Erik, should I merge these changes or we have some further work here?

**Comment by erikruth** [comment]
Go ahead and merge the changes. I am still seeing references to PushButton where I am expecting to see ImageButton so I have not edited those files since you are not done making those changes. Please let me know when those are done and send links to the .md files to review. Thank you.

**Pull request merged**
